### ISSUE TITLE
環境構築

### ISSUE THREAD

**Issue by justice28n** [flutteruniv/happyo#2]
# 環境構築
環境構築が終わったら下のバージョン情報に「flutter doctor」の出力結果をペーストしてください。
終わったら下記チェックボックスにチェックをお願いします。

- [x] @near108 
- [x] @KenjiroTakahashi 
- [x] @koheiMomma 
- [x] @Mimimi-d 

### @near108 
flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm (Rosetta),
    locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

### @KenjiroTakahashi 
[✓] Flutter (Channel dev, 3.1.0-9.0.pre, on macOS 12.4 21F79 darwin-x64, locale
    ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.66.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

### @koheiMomma 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale
    ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version
    32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.48.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

### @Mimimi-d 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm (Rosetta),
  locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by justice28n** [comment]
@KenjiroTakahashi 
環境構築何か詰まってることあれば教えてください。

**Comment by KenjiroTakahashi** [comment]
> @KenjiroTakahashi 環境構築何か詰まってることあれば教えてください。

すみません、遅くなりました。対応済みです。
