### ISSUE TITLE
VideoControllerに必要な機能を洗い出す

### ISSUE THREAD

**Issue by justice28n** [flutteruniv/happyo#21]

**Comment by justice28n** [comment]
動画を操作する機能として何が必要なのか洗い出してほしいです。
機能名、内容、優先度（必須・高・低）くらいはほしいです。
下記表のように整理してもらえると助かります。

| No. | 機能名 | 内容 | 優先度 |
| --- | --- | --- | --- |
| 1 | 再生 | 動画を再生する | 必須 |
| 2 | 字幕 | 字幕をストリームで取得して表示する | 低 |

**Comment by YutaOkazima** [comment]
YouTubeの機能を参考に書き出してみました。
video_playerでの実装は[こちら](https://www.fluttercampus.com/guide/268/play-video-flutter-example/)を参考

| No. | 機能名 | 内容 | 優先度 | video_playerでの実装 |
| --- | --- | --- | --- | --- | 
| 1 | 再生 | 動画を再生する | 必須 |   controller.play(); |
| 2 | 一時停止 | 動画を一時停止する | 必須 | controller.pause(); |
| 3 | シーク | 任意の位置から再生する | 必須 | VideoProgressIndicator(allowScrubbing: true,) |
| 4 | シークバー | 再生位置を表示する | 必須| VideoProgressIndicatorウィジェット |
| 5 | 音量 | 音量を調節する | 必須 | controller.setVolume(0.0); |
| 6 | 再生速度設定 | 再生速度の設定 | 高 |controller.setPlaybackSpeed |
| 7 | 全画面表示 | 全画面表示 | 高 |chewieを使ったらいける?[^3] |
| 8 | 次の動画前の動画へ |次や前の動画へ | 高 | ??? |
| 9 | 字幕 | 字幕をストリームで取得して表示する | 低 |現状ローカルファイルからただ読み込むだけなら可能、ストリームは別途実装が必要[^5]|
| 10 | 画質設定 | 動画の画質を設定する | 低 |???|
| 11 | ループ | 動画をループ再生する | 低|_controller.setLooping(true);[^6]
| 12 | 動画の時間表示 | 動画の全部の長さを表示する | 高 |controller.value.duration|
| 13 | 再生時点の時間表示 | 現在再生している動画の現時点の時間を表示する | 高 | UI自作で実装可能[^2] |
| 14 | 15秒スキップ、巻き戻し | 動画を15秒スキップ巻き戻しをする | 高 | いけそう(実装できてません、、)[^4] |

#### 実装の参考資料
[^2]: https://stackoverflow.com/questions/60249930/how-to-show-current-play-time-of-video-when-using-video-player-plugin-in-flutter
[^3]: https://stackoverflow.com/questions/52431109/flutter-video-player-fullscreen
[^4]: https://www.youtube.com/watch?v=Xo939-OYQbM&ab_channel=JohannesMilke
[^5]: https://logmi.jp/tech/articles/324803
[^6]: https://www.egao-inc.co.jp/programming/flutter_movie_widget/

**Comment by YutaOkazima** [comment]
@near108 

明日から二日間旅行に行くので進捗報告のコメントです。

chewieや調べきれていないことがありますが、確認よろしくお願いします。

**Comment by justice28n** [comment]
@Mimimi-d
洗い出しおよび、調査までしていただきありがとうございました。
洗い出しとしてはこれで問題ないと思います。
実装方法について、今回わからなかったものはissueに上げて、今後のタスクとして棚上げします。

以下、気になった点をコメントしておきます。

> 7. 全画面表示
> 下記動画、参考にならないでしょうか？
> https://www.youtube.com/watch?v=x0ZNQ0YXyfE
> 
> 8. 次の動画、前の動画
> 関数を引数に受ける形かなと思ってます。
> 
> 9. 字幕
> どうにか別途実装はできそうですね。
> 工数がかかりそうなので、共同開発のスコープからは外す。（issueには上げておきます）
> 優先度は低でOKです。
> 
> 10. 画質設定
> vide_playerのパッケージには実装されていないため、別途実装が必要。
> 工数がかかりそうなので、共同開発のスコープからは外す。（issueには上げておきます）
> やるとしても @Mimimi-d さんの就活が終わってから。
> 
> 11. ループ
> 優先度としては一番低いので、共同開発のスコープからは外す。
> 
> 13. 再生時点の時間表示
> 下記、positionの値で取得できないかな。（一応issueに上げておきます）
> https://pub.dev/documentation/video_player/latest/video_player/VideoPlayerValue/position.html
> 
> 14. スキップ、巻き戻し
> スキップ、巻き戻しの秒数をユーザー設定の値として動的な値としたいです。
> 実装方法については参考URLを確認し理解しました。いけそうですね！（issueはいらないかな）
