### ISSUE TITLE
YouTubeの動画を再生できるか調査する

### ISSUE THREAD

**Issue by justice28n** [flutteruniv/happyo#4]
YouTubeの動画を再生するのに使用するライブラリがいくつか種類あると思うので、種類を洗い出し、1番メジャーなライブラリをまずは使ってみる。

**Comment by mmmkx** [comment]
| No. | 機能名 | 内容 | 優先度  | YoutubePlayerIFrameでの実装 | YoutubePlayerFlutterでの実装
| --- | --- | --- | --- | --- |  --- | 
| 1 | 再生 | 動画を再生する | 必須 |  play() | play() |
| 2 | 一時停止 | 動画を一時停止する | 必須 | pause() | pause() 
| 3 | シーク | 任意の位置から再生する | 必須 | seekTo(position, {allowSeekAhead}) | seekTo(Duration position, {bool allowSeekAhead = true}) |
| 4 | シークバー | 再生位置を表示する | 必須| シークバー | シークバー |
| 5 | 音量 | 音量を調節する | 必須 | setVolume(volume) | setVolume(volume) |
| 6 | 再生速度設定 | 再生速度の設定 | 高 |setPlaybackRate(rate) | setPlaybackRate(rate) |
| 7 | 全画面表示 | 全画面表示 | 高 | onEnterFullScreen() | toggleFullScreenMode() |
| 8 | 次の動画前の動画へ |次や前の動画へ | 高 | nextVideo(),previousVideo() | toggleFullScreenMode() |
| 9 | 字幕 | 字幕をストリームで取得して表示する | 低 | ??? | ??? |
| 10 | 画質設定 | 動画の画質を設定する | 低 | playbackquality | ??? |
| 11 | ループ | 動画をループ再生する | 低| setLoop(loop) | ??? |
| 12 | 動画の時間表示 | 動画の全部の長さを表示する | 高 | シークバー | シークバー |
| 13 | 再生時点の時間表示 | 現在再生している動画の現時点の時間を表示する | 高 | シークバー | シークバー |
| 14 | 15秒スキップ、巻き戻し | 動画を15秒スキップ巻き戻しをする | 高 | ??? | ??? |


参考
・IFrame
https://pub.dev/packages/youtube_player_iframe
https://flutter.gakumon.jp/entry/flutter-youtube-player

・Flutter
https://pub.dev/packages/youtube_player_flutter
https://pub.dev/documentation/youtube_player_flutter/latest/youtube_player_flutter/YoutubePlayerController-class.html
https://github.com/sarbagyastha/youtube_player_flutter/tree/master/packages/youtube_player_flutter/example

・その他
https://qiita.com/chiaki-kjwr/items/0bacb45e3e1f88d8f4c1
